# 视频模式 Pipeline 配置
# 支持实时处理、EIS、VSR等功能

pipeline:
  name: "video_mode"
  description: "视频模式，支持实时处理、EIS、VSR等高级功能"
  mode: "video"
  
  # 节点配置
  nodes:
    # RAW输入节点
    raw_input:
      type: "RawInputNode"
      config:
        input_type: "simulation"  # file, simulation, camera
        bayer_pattern: "rggb"
        width: 1920
        height: 1080
        bit_depth: 10
        noise_model:
          enabled: true
          read_noise: 1.5
          shot_noise: 0.08
          dark_current: 0.005
        motion_simulation:
          enabled: true
          motion_type: "jitter"
          intensity: 0.05
    
    # RAW预处理节点（轻量级）
    raw_preproc:
      type: "RawPreprocNode"
      implementation: "classic"
      config:
        bpc_enabled: true
        blc_enabled: true
        lsc_enabled: false  # 视频模式关闭LSC以提高性能
        lsc_method: "classic"
    
    # 去马赛克节点（轻量级）
    demosaic:
      type: "DemosaicNode"
      implementation: "classic"  # 视频模式使用经典方法以保证实时性
      config:
        classic_method: "bilinear"
        quality_enhancement:
          enabled: false  # 关闭质量增强以提高性能
    
    # 白平衡节点
    awb:
      type: "AWBNode"
      implementation: "classic"
      config:
        method: "gray_world"
        temperature: 5500
        tint: 0.0
        adaptive: true  # 视频模式启用自适应白平衡
    
    # 色彩校正节点
    color_correction:
      type: "ColorCorrectionNode"
      implementation: "classic"
      config:
        method: "matrix"
        ccm_matrix: [[1.4, -0.2, -0.2], [-0.1, 1.3, -0.2], [-0.1, -0.1, 1.2]]
    
    # 伽马校正节点
    gamma:
      type: "GammaNode"
      implementation: "classic"
      config:
        gamma: 2.2
        method: "power_law"
    
    # 降噪节点（轻量级）
    denoising:
      type: "DenoisingNode"
      implementation: "classic"
      config:
        method: "bilateral"
        strength: 0.1  # 视频模式降低降噪强度
        temporal_enabled: true  # 启用时域降噪
    
    # EIS运动估计节点
    eis_motion:
      type: "EISMotionNode"
      implementation: "hybrid"
      config:
        method: "optical_flow"  # optical_flow, feature_tracking, ai
        ai_model_path: "models/eis_motion_net.onnx"
        window_size: 15
        max_displacement: 30
        smoothing_factor: 0.8
    
    # EIS重采样节点
    eis_warp:
      type: "EISWarpNode"
      implementation: "classic"
      config:
        method: "affine"
        interpolation: "bilinear"
        border_mode: "reflect"
    
    # 超分辨率节点
    vsr:
      type: "VSRNode"
      implementation: "ai"
      config:
        method: "real_time"  # real_time, quality, ai
        ai_model_path: "models/vsr_rt_net.onnx"
        scale_factor: 2
        quality_mode: "fast"  # fast, balanced, quality
    
    # 锐化节点（轻量级）
    sharpening:
      type: "SharpeningNode"
      implementation: "classic"
      config:
        method: "unsharp_mask"
        strength: 0.2
        radius: 0.8
    
    # 输出节点
    output:
      type: "OutputNode"
      config:
        format: "yuv420"  # yuv420, rgb, h264
        quality: 90
        save_path: "output/video_{timestamp}.mp4"
        fps: 30
    
    # 预览输出节点（降采样）
    preview_output:
      type: "PreviewOutputNode"
      config:
        format: "rgb"
        scale_factor: 0.5  # 降采样到一半尺寸
        quality: 80
        save_path: "preview/video_preview_{timestamp}.jpg"
  
  # 连接配置
  connections:
    - from: "raw_input.output"
      to: "raw_preproc.input"
    
    - from: "raw_preproc.output"
      to: "demosaic.input"
    
    - from: "demosaic.output"
      to: "awb.input"
    
    - from: "awb.output"
      to: "color_correction.input"
    
    - from: "color_correction.output"
      to: "gamma.input"
    
    - from: "gamma.output"
      to: "denoising.input"
    
    - from: "denoising.output"
      to: "eis_motion.input"
    
    - from: "eis_motion.output"
      to: "eis_warp.input"
    
    - from: "eis_warp.output"
      to: "vsr.input"
    
    - from: "vsr.output"
      to: "sharpening.input"
    
    - from: "sharpening.output"
      to: "output.input"
    
    # 预览分支
    - from: "sharpening.output"
      to: "preview_output.input"
  
  # 执行配置
  execution:
    mode: "streaming"  # single, batch, streaming
    batch_size: 1
    enable_parallel: true
    enable_caching: false  # 视频模式关闭缓存以节省内存
    
  # 质量分析配置
  quality_analysis:
    enabled: true
    metrics:
      - "psnr"
      - "ssim"
      - "lpips"
    reference_path: "reference/video_ground_truth.mp4"
    real_time_metrics: true  # 启用实时质量评估
    
  # 性能配置
  performance:
    target_fps: 30.0  # 视频模式，30fps
    max_latency_ms: 33  # 33ms对应30fps
    enable_profiling: true
    enable_optimization: true
    memory_limit_mb: 1024  # 限制内存使用
    
  # EIS配置
  eis:
    enabled: true
    stabilization_strength: 0.7
    smoothing_window: 15
    max_crop_ratio: 0.1  # 最大裁剪比例
    
  # VSR配置
  vsr:
    enabled: true
    target_resolution: [3840, 2160]  # 4K输出
    quality_mode: "balanced"  # fast, balanced, quality
    enable_temporal_consistency: true
